apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a-deployment
  labels:
    app: service-a-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service-a-deployment
  template:
    metadata:
      labels:
        app: service-a-deployment
    spec:
      containers:
      - name: service-a-deployment
        image: josephrechdiner/service-a:v1
        ports:
        - containerPort: 8000
        env:
        - name: INTERNAL_URL
          value: "http://service-b-service:9060/ingest"
