apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-b-deployment
  labels:
    app: service-b-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service-b-deployment
  template:
    metadata:
      labels:
        app: service-b-deployment
    spec:
      containers:
      - name: service-b-deployment
        image: taktuk/service-b:v1
        ports:
        - containerPort: 9060
        env:
        - name: SERVICE_C_URL
          value: "http://service-c-service:8080/records"
